language: cpp
sudo: required
dist: trusty
compiler:
- g++
os:
- linux

before_install:
- echo $LANG
- echo $LC_ALL
- if [ $TRAVIS_OS_NAME == linux ]; then ./scripts/dependencies.sh; fi

script:
- if [ $TRAVIS_OS_NAME == linux ]; then ./scripts/build.sh

env:
  global:
  - LANG="en_US.UTF-8"

